=== codeGraphK/parchis_Cartas/styleSourceRules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.monproyect.es" targetNamespace="http://www.monproyect.es" elementFormDefault="qualified">
<xs:element name="estilos">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="estilo" maxOccurs="unbounded" type="estiloType"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<!-- tipo de elemento para todos los estilos -->

<xs:complexType name="estiloType">
    <xs:sequence>
        <xs:element name="colores" type="coloresType" />
        <xs:element name="texto" type="textoType" />
        <xs:element name="imagenes" type="imagenesType" />
    </xs:sequence>
    <xs:attribute name="num" type="xs:integer"/>
</xs:complexType>

<!-- declaración de los tres elementos hijos de estilo -->

<xs:complexType name="coloresType">
    <xs:sequence>
        <xs:element name="principal" type="coloresChildType"/>
        <xs:element name="comPrincipal" type="coloresChildType"/>
        <xs:element name="secundario" type="coloresChildTypeExt"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="textoType">
    <xs:sequence>
        <xs:element name="segundaPantalla" type="pantallaTypeSub"/>
        <xs:element name="terceraPantalla" type="pantallaTypeTwoNames"/>
        <xs:element name="cuartaPantalla" type="pantallaTypeFourNames"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="imagenesType">
    <xs:sequence>
        <xs:element name="logo" type="imagenesChildType"/>
        <xs:element name="cartaBack" type="imagenesChildType"/>
        <xs:element name="curvaMayor" type="xs:string"/>
        <xs:element name="curvaMenor" type="xs:string"/>
        <xs:element name="primeraIlustracion" type="xs:string"/>
        <xs:element name="segundaIlustracion" type="xs:string"/>
    </xs:sequence>
</xs:complexType>

<!-- declaración de los tipos de los hijos de colores -->

<xs:complexType name="coloresChildType">
    <xs:sequence>
        <xs:element name="regular" type="colorSimpleRestrict"/>
        <xs:element name="oscuro" type="colorSimpleRestrict"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="coloresChildTypeExt">
    <xs:complexContent>
        <xs:extension base="coloresChildType">
            <xs:sequence>
                <xs:element name="claro" type="colorSimpleRestrict"/>
            </xs:sequence>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>

<!-- restricciones de tipo simple -->

<xs:simpleType name="colorSimpleRestrict">
    <xs:restriction base="xs:string">
        <xs:pattern value="#([a-fA-F0-9]{6})"></xs:pattern>
    </xs:restriction>
</xs:simpleType>

<!-- declaración de los hijos de texto -->

<xs:complexType name="pantallaTypeDef">
    <xs:sequence>
        <xs:element name="titulo" type="tituloType"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="tituloType">
    <xs:sequence>
        <xs:element name="valor" type="xs:string"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="pantallaTypeSub">
    <xs:complexContent>
        <xs:extension base="pantallaTypeDef">
            <xs:sequence>
                <xs:element name="subtitulo" type="tituloType"/>
            </xs:sequence>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>

<xs:complexType name="pantallaTypeTwoNames">
    <xs:complexContent>
        <xs:extension base="pantallaTypeDef">
            <xs:sequence>
                <xs:element name="nombre" minOccurs="2" maxOccurs="2" type="nombreType"/>
            </xs:sequence>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>

<xs:complexType name="pantallaTypeFourNames">
    <xs:complexContent>
        <xs:extension base="pantallaTypeDef">
            <xs:sequence>
                <xs:element name="nombre" minOccurs="4" maxOccurs="4" type="nombreType"/>
            </xs:sequence>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>

<!-- restricciones tipo simple -->

<xs:simpleType name="nombreType">
    <xs:restriction base="xs:string">
        <xs:pattern value="[a-zA-Z\s]{3,15}"></xs:pattern>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="margenType">
    <xs:restriction base="xs:string">
        <xs:pattern value="[0-9]?[0-9]((.[0-9])?[0-9]?)?vh"></xs:pattern>
    </xs:restriction>
</xs:simpleType>

<!-- declaración de los hijos de imágenes -->

<xs:simpleType name="imagenesChildType">
    <xs:restriction base="xs:string">
        <xs:pattern value="url[(].+[)]"></xs:pattern>
    </xs:restriction>
</xs:simpleType>

</xs:schema>

=== codeGraphK/parchis_Cartas/styleSource.xml
<?xml version="1.0" encoding="UTF-8"?>
<estilos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.monproyect.es" xsi:schemaLocation="http://www.monproyect.es styleSourceRules.xsd">
    <estilo num="1">
        <colores>
            <principal>
                <regular>#1B998B</regular>
                <oscuro>#255957</oscuro>
            </principal>
            <comPrincipal>
                <regular>#EFFFF5</regular>
                <oscuro>#E8F7EE</oscuro>
            </comPrincipal>
            <secundario>
                <regular>#F46036</regular>
                <oscuro>#CE3F19</oscuro>
                <claro>#FEF0EC</claro>
            </secundario>
        </colores>
        <texto>
            <segundaPantalla>
                <titulo>
                    <valor>Ridondanza S.A</valor>
                </titulo>
                <subtitulo>
                    <valor>Più ridondanza rispetto agli stipendi</valor>
                </subtitulo>
            </segundaPantalla>
            <terceraPantalla>
                <titulo>
                    <valor>Le lettere</valor>
                </titulo>
                <nombre>Gior</nombre>
                <nombre>Hugo</nombre>
            </terceraPantalla>
            <cuartaPantalla>
                <titulo>
                    <valor>Parcheesi</valor>
                </titulo>
                <nombre>Quan</nombre>
                <nombre>Petto</nombre>
                <nombre>Pevre</nombre>
                <nombre>Caste</nombre>
            </cuartaPantalla>
        </texto>
        <imagenes>
            <logo>url(Ejemplo)</logo>
            <cartaBack>url('img/backCardFirst.svg')</cartaBack>
            <curvaMayor>img/purpleSectionFirst.svg</curvaMayor>
            <curvaMenor>img/tealSectionFirst.svg</curvaMenor>
            <primeraIlustracion>img/primerUnDrawFirst.svg</primeraIlustracion>
            <segundaIlustracion>img/segundoUnDrawFirst.svg</segundaIlustracion>
        </imagenes>
    </estilo>
    <estilo num="2">
        <colores>
            <principal>
                <regular>#4C2D3A</regular>
                <oscuro>#311D25</oscuro>
            </principal>
            <comPrincipal>
                <regular>#F6EEDF</regular>
                <oscuro>#DED6C6</oscuro>
            </comPrincipal>
            <secundario>
                <regular>#058ED9</regular>
                <oscuro>#04689E</oscuro>
                <claro>#BAE0F4</claro>
            </secundario>
        </colores>
        <texto>
            <segundaPantalla>
                <titulo>
                    <valor>Poisson à L'Orange</valor>
                </titulo>
                <subtitulo>
                    <valor>Je préfère une glace à la saucisse</valor>
                </subtitulo>
            </segundaPantalla>
            <terceraPantalla>
                <titulo>
                    <valor>Des Lettres</valor>
                </titulo>
                <nombre>Ange</nombre>
                <nombre>Rome</nombre>
            </terceraPantalla>
            <cuartaPantalla>
                <titulo>
                    <valor>Parch'si de Base</valor>
                </titulo>
                <nombre>Char</nombre>
                <nombre>Lotte</nombre>
                <nombre>Abrah</nombre>
                <nombre>Amow</nombre>
            </cuartaPantalla>
        </texto>
        <imagenes>
            <logo>url(Ejemplo)</logo>
            <cartaBack>url('img/backCard.svg')</cartaBack>
            <curvaMayor>img/purpleSection.svg</curvaMayor>
            <curvaMenor>img/tealSection.svg</curvaMenor>
            <primeraIlustracion>img/primerUnDraw.svg</primeraIlustracion>
            <segundaIlustracion>img/segundoUnDraw.svg</segundaIlustracion>
        </imagenes>
    </estilo>
    <estilo num="3">
        <colores>
            <principal>
                <regular>#4f304b</regular>
                <oscuro>#22031f</oscuro>
            </principal>
            <comPrincipal>
                <regular>#ffe6ff</regular>
                <oscuro>#e8d2e8</oscuro>
            </comPrincipal>
            <secundario>
                <regular>#00c893</regular>
                <oscuro>#00805e</oscuro>
                <claro>#e9fef4</claro>
            </secundario>
        </colores>
        <texto>
            <segundaPantalla>
                <titulo>
                    <valor>Estilo inicial</valor>
                </titulo>
                <subtitulo>
                    <valor>Este es el valor por defecto</valor>
                </subtitulo>
            </segundaPantalla>
            <terceraPantalla>
                <titulo>
                    <valor>Son Cartas</valor>
                </titulo>
                <nombre>Paco</nombre>
                <nombre>Pepe</nombre>
            </terceraPantalla>
            <cuartaPantalla>
                <titulo>
                    <valor>Este Parchis</valor>
                </titulo>
                <nombre>Lucho</nombre>
                <nombre>Perez</nombre>
                <nombre>Henry</nombre>
                <nombre>Diego</nombre>
            </cuartaPantalla>
        </texto>
        <imagenes>
            <logo>url(Ejemplo)</logo>
            <cartaBack>url('img/backCard.svg')</cartaBack>
            <curvaMayor>img/purpleSection.svg</curvaMayor>
            <curvaMenor>img/tealSection.svg</curvaMenor>
            <primeraIlustracion>img/primerUnDraw.svg</primeraIlustracion>
            <segundaIlustracion>img/segundoUnDraw.svg</segundaIlustracion>
        </imagenes>
    </estilo>
</estilos>
